language: csharp

#dotnet cli require Ubuntu 14.04
sudo: required
dist: trusty

#dotnet cli require OSX 10.10
osx_image: xcode7.3.1

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

os:
  - osx
  - linux

dotnet: 2.0.2

env:
  matrix:
    - CLI_VERSION=2.0.2

before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then ./tooling/configure-dotnet-cli-osx.sh; fi
  # Download script to install dotnet cli
  - curl -L --create-dirs https://raw.githubusercontent.com/dotnet/cli/release/2.0.0/scripts/obtain/dotnet-install.sh -o ./scripts/obtain/install.sh
  - find ./scripts -name "*.sh" -exec chmod +x {} \;
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - ./scripts/obtain/install.sh --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR" --no-path
  # add dotnet to PATH
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"

script:
  - ./build.sh
