version: '{build}'
image: Visual Studio 2015
configuration: Release
install:
  - ps: ./Install.ps1
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/FsMessageTemplates.*.nupkg
- path: artifacts/FsMtParser.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: ZdlULX6DI2b/fKecXcFFuKZmMP+q2lz+us4pAeGqFl7mK0Be2/hG7LDSfZgIgAKI
  skip_symbols: true
  on:
    branch: /^(dev|master)$/

